
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqccayfzcxuadkzohgzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxY2NheWZ6Y3h1YWRrem9oZ3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDU0NzQsImV4cCI6MjA1ODY4MTQ3NH0.voJsuUs1noG3SGq97VSIFhuVXC0SK-Z99CjJMRlY3I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
